apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: calico
spec:
  clusterSelector:
    matchLabels:
      cni: calico
  repoURL: https://docs.tigera.io/calico/charts
  chartName: tigera-operator
  version: ${CALICO_VERSION}
  releaseName: projectcalico
  namespace: tigera-operator
  valuesTemplate: |
    installation:
      cni:
        type: Calico
        ipam:
          strictAffinity: true
          type: Calico
      calicoNetwork:
        bgp: Disabled
        windowsDataplane: HNS
        mtu: 1350
        ipPools:
        ipPools:{{range $i, $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}
        - cidr: {{ $cidr }}
          encapsulation: VXLAN{{end}}
      serviceCIDRs: {{range $i, $cidr := .Cluster.spec.clusterNetwork.services.cidrBlocks }}
        - {{ $cidr }}{{end}}
      registry: docker.io/
    # Image and registry configuration for the tigera/operator pod.
    tigeraOperator:
      image: tigera-operator
      registry: jsturtevant
      version: latest
    calicoctl:
      image: mcr.microsoft.com/oss/calico/ctl