---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["2001:1234:5678:9abe::/64"]
    services:
      cidrBlocks: ["fd00::/108"]
    