installation:
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
    mtu: 1350
    ipPools:
    - cidr: 192.168.0.0/16
      encapsulation: VXLAN
    windowsDataplane: HNS
  serviceCIDRs: 
    - 10.96.0.0/12 # must match cluster service CIDR (this is the default)
  registry: mcr.microsoft.com/oss
# Image and registry configuration for the tigera/operator pod.
tigeraOperator:
  image: tigera/operator
  registry: mcr.microsoft.com/oss
calicoctl:
  image: mcr.microsoft.com/oss/calico/ctl
